---
collections:
  - name: community.general
    version: 12.2.0
  - name: community.sops
    version: 2.2.7
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: kubernetes.core
    version: 6.2.0
  - name: devsec.hardening
    version: 10.5.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.6.2
  - name: githubixx.ansible_role_wireguard
    src: https://github.com/githubixx/ansible-role-wireguard.git
    version: 18.3.0
