---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 43.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    alertmanager:
      enabled: false
    kube-state-metrics:
      metricLabelsAllowlist:
        - "persistentvolumeclaims=[*]"
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
    grafana:
      enabled: false
    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance
    kubeApiServer:
      enabled: true
    # kubeControllerManager:
    #   enabled: true
    #   endpoints:
    #     - 192.168.42.10
    #     - 192.168.42.11
    #     - 192.168.42.12
    # kubeScheduler:
    #   enabled: true
    #   endpoints:
    #     - 192.168.42.10
    #     - 192.168.42.11
    #     - 192.168.42.12
    # kubeProxy:
    #   enabled: true
    #   endpoints:
    #     - 192.168.42.10
    #     - 192.168.42.11
    #     - 192.168.42.12
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        replicas: 1
        replicaExternalLabelName: __replica__
        externalLabels:
          cluster: home-ops
        podAntiAffinity: hard
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        retention: 2h
        retentionSize: 1GB
        enableAdminAPI: true
        walCompression: true
        # storageSpec:
        #   volumeClaimTemplate:
        #     spec:
        #       storageClassName: ceph-block
        #       resources:
        #         requests:
        #           storage: 50Gi
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 1000Mi
        remoteWrite:
          - url: "${GRAFANA_PROMETHEUS_URL}"
            basicAuth:
              username:
                key: GRAFANA_USERNAME
                name: grafana-creds
              password:
                key: GRAFANA_PASSWORD
                name: grafana-creds
