---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/apps/observability/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app alertmanager-config
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/apps/observability/kube-prometheus-stack/alertmanager-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
