---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app oauth2-proxy
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      version: 7.8.1
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1

    config:
      clientID: ""
      clientSecret: ""
      cookieSecret: ""
      configFile: |
        provider = "google"
        email_domains = ["*"]
        authenticated_emails_file = "/etc/oauth2-proxy/authenticated-emails.txt"
        cookie_secure = true
        cookie_httponly = true
        cookie_expire = "168h"
        cookie_refresh = "1h"
        cookie_domains = [".kaminek.me"]
        whitelist_domains = [".kaminek.me"]
        pass_access_token = true
        pass_authorization_header = true
        set_authorization_header = true
        set_xauthrequest = true
        reverse_proxy = true
        skip_provider_button = false
        redirect_url = "https://oauth.kaminek.me/oauth2/callback"

    authenticatedEmailsFile:
      enabled: true
      restricted_access: |
        kaminek92@gmail.com

    extraEnv:
      - name: OAUTH2_PROXY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy
            key: OAUTH2_PROXY_CLIENT_ID
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy
            key: OAUTH2_PROXY_CLIENT_SECRET
      - name: OAUTH2_PROXY_COOKIE_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy
            key: OAUTH2_PROXY_COOKIE_SECRET

    ingress:
      enabled: true
      className: external
      hosts:
        - oauth.kaminek.me
      tls:
        - hosts:
            - oauth.kaminek.me
          secretName: oauth-kaminek-me-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: ingress.kaminek.me

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
