---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
