apiVersion: v1
kind: Secret
metadata:
    name: github-token-secret
    labels:
        details: github PAT flux-notification
type: Opaque
data:
    token: ENC[AES256_GCM,data:TTYzA7/jE3/eNH24PrDko0J+j8LsEyC9xypfbkw6rPo21MJtQSOy0P/5xP+yi585pvAyObzo9lcX/r1EIwk8ExOA2M/5VHdQVstNn5a42osNpLs4DXtUYJGxUi41komR/J3IymJ4eD1XEoG6cOEZFGP2Q2HZ4hDoZyDwJQ==,iv:ixUTnh90EUereAzZUDprBMWDy7Ncg91HeL7s9VZBcws=,tag:qP8y+ZWawNUpqH2te6x3OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUmhBNWx4V0VCYWZtMlEx
            YkJXb3ZBbzJFOE9WT3E0dXRRbllrNStXK21FCm5yWVZQY0tzZDZ0TXdKNitoZlVY
            OGVKd3Jrd2k3VWtZWml0L3RibUVwSDgKLS0tIE5TVnB1aDNmTnR1TXhvcFpucWlk
            eVZTTlU3UFBxQVVWUTJNQmR6OGxjOGcKtomJhycWW7WfmmqvI17nSF6+gIZE+Tvr
            XL1MvEQI3aByVcqpSaWNu13eGSB5zWI500UQjL/Gl5iUv2obtra/PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T14:14:02Z"
    mac: ENC[AES256_GCM,data:t1AvAVaQXDFcHOW7Bkhs6h89yF296gLY4rfNaI4oXCBbXWmMXYZ1qbfS63MNKpoGXOiMJ3PjJtELqGaz1qmou3ZW7ccsIe7nv5uMcjP4Las9VLMbmed8bpZsEkWgGzXQgW2AXhYqYeUS+cpv2lFLVNMbOTjtKQutBqS7HpEsXZI=,iv:HJG3+90QG2MSv44RD8RjFAChG9A3evruATnkleq6LiU=,tag:ZWBa1vF8QYweGFFjCGBuBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
