apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-secret
type: Opaque
data:
    CF_API_TOKEN: ENC[AES256_GCM,data:d+av9WPgaxxDoabHzd7amBCpmpZpDK0TnmJkafnpbIUE+tPAAMqpEXKZgPkvu6Zdd7u9CDSS9mI=,iv:Aboh7wYXOAK+phePVVor+NxYOT85lNzicJYIg7wSjJQ=,tag:UcG/z0c9/+/4o3lB4Xy1vw==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:gajoCCI5++S0AVPAoDJZreASOR4D9ubm,iv:ddKK8bfNByy2CE05N1LDXmM7DhyEREBNv1VpkJNMJlc=,tag:2i6gptf4baqAbG1LaCdqbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQzVtZWZpR2llQUhoTFRq
            OHhkbThnSUJqSGVHSGRWbWdNSEltUDhKTDFFCkxPYlB0VEtqRENscFlhWEx0VzFX
            NFNHMzBVcnpYS1VibGh3VVlTOFFRcncKLS0tIHR1Q2hsMVNvZnJ3R3Q4V1hpNUlL
            VjlKSlNvKzBMM3FES1dzc1lUWDdoVW8KkrQger6Cxt5KNRgEYoy/0f1hIAQITWzR
            h+gxzCWyt0+zU/GXve7yqVyz5IiwfHxUo8DitMMnN8uJpoIyHiOnqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T14:48:10Z"
    mac: ENC[AES256_GCM,data:fd5tMBgJLVRbJI6YQSJjaaOi4+bIPPYx9v51YXvJlsWOGTZoOKHfGckW/o/7QHivZX4kW/nqJBOWGrVf+tU8iiJkk3kXuM6zHwjZNg70TuIjOR//EX1zxKvzjO9znPTd249/ZB7/UHJV0oWueLDqmV0TgysmJr8cx4SIYCjShaU=,iv:gC8WkgagmFzQJbBXwVOvU9eu/4vdN7o/cmtZunym/9U=,tag:hGgiTpKe6/a9UJqEGJIQCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
