---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.1.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: prometheus-operator-crds
      namespace: observability
  valuesFrom:
    - kind: ConfigMap
      name: ksm-helm-values
  values:
    crds:
      enabled: false
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      serviceMonitor:
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: alertmanager.kaminek.me
          cert-manager.io/cluster-issuer: letsencrypt-production
        ingressClassName: external
        hosts: ["alertmanager.kaminek.me"]
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.kaminek.me
        pathType: Prefix
      alertmanagerSpec:
        useExistingSecret: true
        configSecret: alertmanager-secret
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources:
                requests:
                  storage: 500Mi
    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          # Drop high cardinality labels
          - action: labeldrop
            regex: (uid)
          - action: labeldrop
            regex: (id|name)
          - action: drop
            sourceLabels: ["__name__"]
            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
        cAdvisorRelabelings:
          - action: replace
            sourceLabels: [__metrics_path__]
            targetLabel: metrics_path
          - action: replace
            targetLabel: cluster
            replacement: homelab
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
    kubeApiServer:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          # Drop high cardinality labels
          - action: drop
            sourceLabels: ["__name__"]
            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
          - action: drop
            sourceLabels: ["__name__"]
            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
    coreDns:
      serviceMonitor:
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
    kubeControllerManager:
      enabled: true
      serviceMonitor:
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
      endpoints: &control-plane
        - 10.32.0.100
        - 10.32.0.101
        - 10.32.0.102
    kubeEtcd:
      enabled: true
      endpoints: *control-plane
      serviceMonitor:
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
    kubeScheduler:
      enabled: true
      endpoints: *control-plane
      serviceMonitor:
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
    kubeProxy:
      enabled: false
      serviceMonitor:
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
    prometheus:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: prometheus.kaminek.me
          cert-manager.io/cluster-issuer: letsencrypt-production
        ingressClassName: external
        hosts: ["prometheus.kaminek.me"]
        pathType: Prefix
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.kaminek.me
      prometheusSpec:
        scrapeInterval: 30s # Must match interval in Grafana Helm chart
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        enableAdminAPI: true
        walCompression: true
        enableFeatures:
          - auto-gomemlimit
          - memory-snapshot-on-shutdown
          - new-service-discovery-manager
        retention: 14d
        retentionSize: 50GB
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 1500Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources:
                requests:
                  storage: 50Gi
    nodeExporter:
      enabled: true
    prometheus-node-exporter:
      fullnameOverride: node-exporter
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
            - action: replace
              targetLabel: cluster
              replacement: homelab
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
      metricLabelsAllowlist:
        - pods=[*]
        - deployments=[*]
        - persistentvolumeclaims=[*]
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
            - action: replace
              targetLabel: cluster
              replacement: homelab
    prometheusOperator:
      serviceMonitor:
        relabelings:
          - action: replace
            targetLabel: cluster
            replacement: homelab
    grafana:
      enabled: false
