apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials-secret
type: Opaque
stringData:
    grafana-loki-endpoint: ENC[AES256_GCM,data:QAui9HXquBExqQYutenmBsmJTlX7GBOj8x9RUIeIDV8j,iv:w5Np2fLSrw+TacmaRklXXf94cdG1QSXsVN1YQ2tvlYk=,tag:9k44dyNJAovSMkj1mIMmOw==,type:str]
    grafana-loki-user: ENC[AES256_GCM,data:yA2OxDHk,iv:60uJ7jrQiGOYnn1KewW+YXog9U0Ip4ZV5CQHUjVOnQs=,tag:Z6t5J1CixV2RZBShuUS49w==,type:str]
    grafana-loki-password: ENC[AES256_GCM,data:gGp+IUHYcWi7XtXLaMlSGINT8L2E50SOqUl0dXmXc2ZG7yg3qnvB0lNIMfgVb5kz9Jiflx0hnWBCHNeSLSBk7Qpu9YKXLPfTGo31nDYBTPmtnzva/d5O03WEtt/cEHvh0GDzrflDqN86bqqucEIPVpBOo6e/ZOC/5ACkK/ZdDv+9m7ZUPL7CvQTbca6j29g7,iv:wyDOEduxQZc+Tf3LiKoNx0s5e+tddAiWsoUBsnW+2KM=,tag:DHb4h8Jvi3WtDyB2IoJywg==,type:str]
sops:
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa1BTeXNMRC8yNWhjdGZQ
            Um1XaGdnQXJQSWZKR1JQcUlOUXhzOTdXdlJVCjZOYktHUmZvNGtNVjN0Sjg2WDlj
            R3Z1alg0VUp0WHlaUnRSQ3ViSWVKb0EKLS0tIFBZSW04TFZpdWt2Y1l5ejJHYW41
            eE5KQ2dNVVR1QmtDVWI2K1dMamhNaUEKszixW53teZFvSOd8uZniv9z6N4vwRc42
            QjEnQsVvfRe15aUA8KhQBBuebh16vzicNJ2mTLkPAkLEJi7cl838eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T14:57:10Z"
    mac: ENC[AES256_GCM,data:A91usshyOqDz4HoDZaXh2JvTGjqA7uRcSak9qHUeWh5jax8iwQfiyScu45bA1EjINhRztGNCBStH4tgJgQhkKWOXKLDRNKRZXJKZ9nz0HcoAvzjrcH0fLWo4IrEMokUv4j9mzNF0xHOEnp+3qvFNOXptV8ps8qMWIuh4+qQp/HU=,iv:ZOI/GNpjsdO7PZEj6w+/MGwrKKZebnNwcTKcpgDGX+U=,tag:h5Rxyge02FVcT9EQMIMMwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
