apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials-secret
type: Opaque
stringData:
    grafana-loki-endpoint: ENC[AES256_GCM,data:HpIs//lBxBGt5mRexXWMoDZikfhKmxxSTmD3wHN0f1mJ,iv:BvwZtn+zECCWiTTXBdoTzA89URAli0rrqZkaS/BZ8NM=,tag:jo5EBnPoJ9Rdrh3m0TwVBw==,type:str]
    grafana-loki-user: ENC[AES256_GCM,data:dWEpSWpx,iv:UZcDKqFKFfZqJyxJj/lYhEshiKvzno3vxzj7tQfCXpw=,tag:fTSPzxeqq8s5aOxQxWzpEg==,type:str]
    grafana-loki-password: ENC[AES256_GCM,data:UcNsmJB9JqhzedJPNLTbIYio8aeRSCYnTA/g+W9WjdTEmJMG48CsYC5eUOLISOiVF3lnxuOgsxQvfX0eUnYbgO4l004XPkc+x3GKLUKKcp2cybpymnVRA11Xeosnoerwh5YY2BtjULAxNCEHYPwWwJLpRj9CgdzjNyKF3N+fQGMeeo2WYIq5RGFe+WrJwtaa,iv:Pc6x7tGPedi+J++X9dN/W6+JXeEp3d3KvRQ8bhikvbk=,tag:oMoQdUZachnK3nb7pEronQ==,type:str]
    grafana-tempo-endpoint: ENC[AES256_GCM,data:7KDty15qaQckL/JVc+Sk9OwDs2EtW1kHlGXNFlkEUPDdV9YcexDeyq+GKfHlvfkO4jRylaJmNg==,iv:TrU5ii9v/n4ZJuaFT24z3I5gvg0bBSpW9CnQpNAoFUM=,tag:ddYxmPVN9sTYsUV5AG5YYA==,type:str]
    grafana-tempo-user: ENC[AES256_GCM,data:12YboFEJ,iv:41Fau8fi15OMjis8snZJ5Ouc5xYfU0Y6UMbMI1IxM/w=,tag:JTwO+7t6yGS090JvzOr1vA==,type:str]
    grafana-tempo-password: ENC[AES256_GCM,data:4xW2vl4EeP6SWerIRd6UqYlxk/go5y5gdYPKB9/wxaEFt/W/KxWxmAWjO8VG9e7i8moUELg0ZDC9dxKJQsveTaqiK6e/hvi8q0K3p++U1MzKv6WwPM5o4vVTYkKi31i4IdCV28RKXSrRTHFm5mQVh0bp2mA7zskEgsAN8Igxe+LCRjKAdMM1Goy6UzH0tWbC/FUqJadsJ6Dq4CBOKwzBhLbCbj4=,iv:+GYgJlGngbjQXidOwdUfPJ7sroOM+yDIdUiENneu6Bo=,tag:otIn4Rsiy0wxmDn/ZooYyw==,type:str]
sops:
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1b3MzaldJTkV6YVNaeWNM
            bG03ZHRxSjZGSUtyMzlXd3lyaXpRSnE1L1RNCnZxUTNiMDROc3g5MTJ2cWwyNll5
            dXVoWmxOWDhyZjlWRnczYWloYi9qOGcKLS0tICtvMkZiTUxFd29iaVpFT3ovclAz
            dlkvYlhVeU5DRThZZ2pPa3RXQ0FUS2cKBy22JECX5U5mNTb7RqoChU+ptDD9WkQz
            2vLGNG0n/N9BhpLF5LXQSThZvzUfHAOq/MKv1QRXGMOdber1ko8SKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T14:59:20Z"
    mac: ENC[AES256_GCM,data:ccwWibkcfF7RMyyCTn3Dyr/6XgnyNnvp5TKlUKd/6lopSmIULWpw/nsOJVSl+NEhZPZP1JjLB9qxKQ7Zq0dcZo+QOJmPdwJmUr0ELBDRNlhJKJU9yGjmm1EW8q4I/STozEMtpG+WOBgoRaPsax5UKagw843ZWkm+nHqdpvT7dMI=,iv:J8qngpjo7S6pJfDnCBJkjqVB8vUwu63+7Ez3pEpX1Io=,tag:GE/PNGuLpTyeI/MChtWMvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
