---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-alloy
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: k8s-monitoring
      version: 3.6.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: prometheus-operator-crds
      namespace: observability
  values:
    cluster:
      name: homelab

    # Destinations (replaces externalServices)
    destinations:
      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-gb-south-0.grafana.net/loki/api/v1/push
        auth:
          type: basic
          usernameKey: grafana-loki-user
          passwordKey: grafana-loki-password
        secret:
          create: false
          name: grafana-credentials-secret
          namespace: observability

    # Pod logs (only feature enabled)
    podLogs:
      enabled: true
      destinations:
        - grafana-cloud-logs
      extraStageBlocks: |-
        stage.limit {
          rate  = 500
          burst = 800
        }

    # Disabled features
    clusterMetrics:
      enabled: false
    clusterEvents:
      enabled: false
    nodeLogs:
      enabled: false
    applicationObservability:
      enabled: false
    autoInstrumentation:
      enabled: false
    profiling:
      enabled: false

    # Alloy collectors
    alloy-logs:
      enabled: true

    # Disable bundled components
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-operator-crds:
      enabled: false
    opencost:
      enabled: false
