apiVersion: v1
kind: Secret
metadata:
  name: grafana-pdc-agent
type: Opaque
data:
  cluster: ENC[AES256_GCM,data:LXksCAMCBZfn52eKonqGiuwUxJI=,iv:WgNMmsCkYxlMVuW+zufJYrrAj0czUSurszD885C9mWI=,tag:dtxcG0+3vIg9mMFOS+2B1w==,type:str]
  hosted-grafana-id: ENC[AES256_GCM,data:u0KhG1IrnTQ=,iv:cJjbwJm1t4GVuBpLOlxW17CICqYytH12tTTYhnKotyQ=,tag:Lk8jaicjq0IpAXW3RMOMtA==,type:str]
  token: ENC[AES256_GCM,data:o1oJJrqO5U9QXvFbdvTm71ljQtyxJ7N/bc3aLOf+gqF2r84b0JcTCUiDbRyksJ48/lT7DgyFccWBeWzVzZbGqNsr8MqUg1b7aBpYCjDz8aDCChRXadu0BXHoTUegzNSTx5Hfamq2MD7tdbbOpfveEfIXXKCAoMktblibs1bKozGLheebuHsVUosFGYfn+1Bm3QIshPdC8zsH68oC9COuqByjz3mOEXa51a6CKDd1tJOEV3cu0S21HRrb6FdSGqTbcr1p3GebkHU6lsUI,iv:dnFcgVB3ZSyVisU3c1bYkeu/76EWKF6EAHUEV09OMrw=,tag:2uQwVrmE2S5QNwVWM2nd2Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNFE4am82NjErN3JvZWtn
        Tm9SWHdXLzkvUXdSQlBjRmpuK211MjBpQVdZCmpYWUY4eTREWEZ5R0xBb3hYSXQ3
        YUtjdWRtNmZ4dU4rVVZ6SmZlOTNxNFUKLS0tIFUzUERTWVB0VWFDWFBmeDBONVkx
        TFIxL2FSN25MMmhoazViVmljSjBMaFkKXbXAvka8f8XGw2RDNylg7QQZylKj22xZ
        BaV4ZpW6dULM317e38ncEqvDlVmHU5IhTj6X8hAHr+Ocga7YGCucEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-09T14:59:01Z"
  mac: ENC[AES256_GCM,data:g3EwDYd5wr63YVXDdwPTYy+rqi2j6wqFczTG/2qDE5wzAsO2GBfGeir9CBdAp8aeQLXozsANCltUGxmuH/v0CwJuSIXBloUex1AE4BKnUf1OPEuYuJsjkQEz1h2YpPDHmpo1vZbZ5k/iJ4FMq9QrxsHR5Sj58cMsYlJYwmesz+U=,iv:Kdk8VhjBF9zAvTRv+9xnY/OYmZBwe8Lf+Ae9GX7L/xM=,tag:YXWFuk+2ywSg4Yy7fpBT5w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
