---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: cilium-helm-values
  values:
    autoDirectNodeRoutes: true
    bandwidthManager:
      enabled: true
      bbr: false
    bpf:
      masquerade: true
    bgp:
      enabled: false
    cluster:
      name: homelab
      id: 0
    dashboards:
      enabled: true
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - icmp
          - http
          - port-distribution
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/hostname: hubble.kaminek.me
            cert-manager.io/cluster-issuer: letsencrypt-production
          className: external
          hosts: ["hubble.kaminek.me"]
          tls:
            - secretName: hubble-tls
              hosts:
                - hubble.kaminek.me
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["10.43.0.0/16"]
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDRList: ["fd00::/104"]
        clusterPoolIPv6MaskSize: 120
    ipv4:
      enabled: true
    ipv4NativeRoutingCIDR: "10.42.0.0/16"
    ipv6:
      enabled: false
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: true
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      algorithm: maglev
      mode: dsr
    # localRedirectPolicy: true
    # monitor:
    #   enabled: true
    operator:
      replicas: 1
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    rollOutCiliumPods: true
    routingMode: native
