---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard
spec:
  releaseName: *app
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        pod:
          dnsPolicy: ClusterFirst
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: adguard/adguardhome
              tag: v0.107.71
            env:
              TZ: Europe/Paris
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                add: ["NET_BIND_SERVICE"]
                drop: ["ALL"]
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
      dns:
        controller: main
        type: NodePort
        externalTrafficPolicy: Cluster
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
            nodePort: 53
          dns-udp:
            port: 53
            protocol: UDP
            nodePort: 53
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/hostname: adguard.kaminek.me
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: "https://oauth.kaminek.me/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth.kaminek.me/oauth2/start?rd=$scheme://$host$request_uri"
          hajimari.io/enable: "true"
          hajimari.io/icon: shield-check
          hajimari.io/group: Network
        hosts:
          - host: &uri adguard.kaminek.me
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: adguard-tls
    persistence:
      config:
        existingClaim: adguard-config
        globalMounts:
          - path: /opt/adguardhome/conf
      data:
        existingClaim: adguard-data
        globalMounts:
          - path: /opt/adguardhome/work
