---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app coredns
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # dependsOn:
  #   - name: certificates
  path: ./cluster/apps/kube-system/coredns
  prune: false
  sourceRef:
    kind: GitRepository
    name: infrastructure
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 1m
