apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-secret
type: Opaque
data:
    CF_API_TOKEN: ENC[AES256_GCM,data:D1jH/ZLZaw84ax1chxTYPILV9K2oe3cjfU3BEVm5Sx1FoQf5PT76tb5+0s3s1IhvTk0zil0JbHvZpEOWYvabeGISoanlKcGf,iv:rFkJieYiQqzV5YhdSB2ubb/XXhLi1PvNYrCcoxJwJdA=,tag:sEgkbXBlcvBo0CyrytYMeQ==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:h4+fbqZ5wPryAxlGm2bAM13hEpjEppkqgklJAA==,iv:Crp5JCqyut0C2zTVMatrc9R6pqaug3dEyL1DcI5Atqo=,tag:xryUlIZG3+X0IPJPZA0Q9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb3hBOUlvZEFoNTRkR2dG
            emJiVS8vWnZuVU03cnR5MmhYK3FaYmt5bldvCmdCRU5ZS0xEWkhPajQvaCtEWTBF
            UjYwWDlnUU94b0ZwMHJaSmI2ZTlqdTgKLS0tIERQYUd1QVFjckREL2xpQitYUDBp
            Mnc0N3hHN245dTMxT3NrMlJBZmVucGMKxaJ6Ybt9ay5UUeLqM70An2dHcvVSMscG
            KcBDgLMIPQAvqraL7HFjyna20h0UGHvS73t4sRycGxnUW3u//sfEZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T19:24:34Z"
    mac: ENC[AES256_GCM,data:uUl+b/l2HVeRazls+JDg3ZSNbKOdciAe0gk94fkADbDI/gylpg5GeM+W/Ld2SmF9YUcbyUhUoQeTIIUjNGlte5hrY2mnrglATl6SVdyiswfdJ/W0QRDE1Lj6PzAktkCTVnsiOfFMnoWlYtQ4rrwgZYKbBObum8n3/XX1BSd0Hpo=,iv:6/4O/WJMap6D6y2L8DGIpK2P+dgPZR02NxnWVaclwo0=,tag:+zcS8bpt8xtLsjxCnrn5JQ==,type:str]
    version: 3.13.1
