apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-secret
type: Opaque
data:
    CF_API_TOKEN: ENC[AES256_GCM,data:wKJ4pbFk5zJVBM0BiBMbZ52JfOnCV+e22/U4LKmxDJCdVU6KUUpx8VbCMD6tGaUilo4AJMcF4rg=,iv:s+dPU3hynFLoOVLotOFF6CGVzfWQ2C3gEdKZPWxHlU8=,tag:wy3XqBMS62prObZXs0xKwQ==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:8eq2iyRp3NigYCI3h8pwtxNNfz9PusAELbsKXw==,iv:m3ZZG4WTxdYMYY0IVldoWkWHjlzEuvuqpQdI1A1Zm3k=,tag:Tgx9Ouomuup5uKMJeHFqTw==,type:str]
sops:
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTjJ5N2NDa0tocER1ZWtS
            Y3paQ1lneGIvbUU2MitzbDRrM2g1Yml5MUhrClkzRHR5eEJxdDlSNGdmV3VEc3hT
            VWtwMWVXaTVtRXVubytZTWJYQTNuN1UKLS0tIFZaUHVJUGRwV1hSSkJ5UXZKZFds
            c1d2TWI0OTRjQXplWFBhZm8wRzdRTUkKTOGkRWZV8jp2b9QLkXIkc+mVSoJYp/cf
            QeYfBRtU7g74Qjrk9UkVGc7W0xEzX6eO7+O3UqE574HNWOSLES5TKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T13:45:24Z"
    mac: ENC[AES256_GCM,data:7/ybQpDzGRB7ZrJYxxHTJY1U2huWIBK66L9sj/I9j8XrxBXRE5OjGLBcP5Ax51ZYmcw0QkQ2l24bKOkRt/zKu18muuA99URS3GwTcQUZlT842NM+3Sjz0ojjUd6fBQkPGM174sqeFbyCxfamykVtBN3u8OtFZy+adUPL8YPi5VQ=,iv:H37ioharaaPe3jwSVyOrgFg5QMpFytRcHaVp+EQlWCU=,tag:RuRWnCWt7IrRnjVALi/tlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
