---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
  namespace: database
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: main
  databaseReclaimPolicy: retain
