---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-repositories
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/flux/repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure
