apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
stringData:
    #ENC[AES256_GCM,data:JxcBg/IImLKxyfWQySbGrE91F3lmsErU28/+5Xn7hVU3ro8JPep/0wIpHZyuLjLHzf+TiYZubbFegtdIt8OwIIuLYA0=,iv:Oili2W92jm/6D/yohOn3an/kuhZYlLIK7kWgtcwy1fw=,tag:1HRnyKXLgP86+NNm5GDrxg==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:fsI7Bk7SP4Q=,iv:atKNQwbyQkiAAyHVDadJoDwS98ppEke/N2zUMKtJHUw=,tag:yIzFFErghP1g9F+TzSvmMQ==,type:str] #ENC[AES256_GCM,data:p8ZKa+tBy+7jDF51ZKozh7gU8eOuUeeX9OrEwmnqlPw=,iv:5gXsPq7S4BfznlmNQFNpUyySltM/XCn8G5wSPpEBetc=,tag:/CJ4e9G47hP4cG6uyU1Uxg==,type:comment]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Zw/Jo6g4L/w=,iv:p5mq2sPdGUCBQ4+ILgMFf/bzqdiYSlqhXHTBB5Rpigk=,tag:0fDkEkj+4DBhX4pmElsflw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:I2sJmfClqYU=,iv:DrU5J9mjhgYlWOTQuum2SdgNwRVtAIAJBKoVdZsBPZE=,tag:Ns+PGLfG2KGt9gsMzTgkrw==,type:str] #ENC[AES256_GCM,data:+ndCHt2BbYX/e4ShM13xaeWFjHHq,iv:ux60CslJjN+edN6HmLN2RHo/9FMdZXTODBVBdsR0qU4=,tag:2hZgFhN/yzebzeT7po4Njg==,type:comment]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:VOO1rBgA0HpgbTg=,iv:VfPTKoGDnpr6dX7nrQX3NpBzIizhEIPg3foulBqUGtk=,tag:beovaThfGsy25KfU4d09WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVBDVlRhREZXbklrbTFE
            Lzl5Ry9hQ2xQTUhKWXppR0JXd2NHRCs1TlE0ClhITUhzeWFpUWRFMkxrTFBlOTBu
            SVVTSUFSYnlTWjJwbG1aclVHZmNBeVkKLS0tIGtYME43Zk50c2YxclRONDlxdmZs
            V083U3FVMmlTckZFQnpjZWRGeXFhYUUKQHyoR41FjX+WgFggivB+ONvi7eodLhd2
            D8mqHeynuohoh8kyeJ3SYaV+6dmYPMMpMhgWYEdtswSKvibziEIbGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T15:14:11Z"
    mac: ENC[AES256_GCM,data:3is6oodBKvODTMTBZpIKJBrUMLEBQctdRzC8fstapsXcaRamarOJwH6I3HJytNp3XSvGQ1ziUvA9a82N7JzP7JbbNZqo3D3CMHIrDTAVd08G5i8y/lewtsTrHyh514ZqgmKiYpZuZelHJ2bEKNRoduiZPgSlxtMsVRgC7n+m240=,iv:K5LtKqhTpA4fmpvp3iyp9NpNOxT7xn8NUEzVPh9ZTes=,tag:Fwbj5uqk2oYbOO9bsmiTzw==,type:str]
    version: 3.13.1
