---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: jellystat
  namespace: database
spec:
  name: jellystat
  owner: jellystat
  cluster:
    name: main
  databaseReclaimPolicy: retain
