apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: cnpg-jellystat-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:1LEE+OcbD1wO,iv:u01JYLdXkH6jqp+9F7PSkYxY/mRmwdsv/cJBLDN6lTQ=,tag:7LnDwg58ROnavnb8Kl6AOQ==,type:str]
    password: ENC[AES256_GCM,data:21oksnD7OXxMQLANezfcNhDxBi2AwweYDSpWJI2c7/k=,iv:DnPox8b2heVZLBGAW6o9KE3OVGtb9shIbcZaQHKoqVA=,tag:s+kBYvtmFfQBmfaP31XDQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YjhTK0JwK2x6SVhLRVU3
            c2V3MmJRTDh2bTQrZ2NhYWxkQ0ZaVEEveUFvCkhqMHlGSC93b0ZkYys2MmtpcDI3
            S1dlM2RDZ1M3MEEyM3hHWmlTUEc5cDQKLS0tIElqWVlEOEdNTFJEWDdONytkUjZL
            SzZwN1ZlM3JYZHhPT0NaLzN6ZHJkczgK4hvx5xfgXJUn33h07p0gKiioO3ukokbm
            z+KSgVv9aohgRHr/ai5TpGyQJ6k/3PzsysCwchpeQlr3WTPzZYQxvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T15:14:11Z"
    mac: ENC[AES256_GCM,data:78FrYBK4fELfCXms60VzLf8VGYCXUcigjxAa/TcYfSJaOI0Allql9PKHlg42kslyb0tZuKxodNwnkjXQ0jIc+iW+WEFqUB5m1RFjwV4v7dvES1G4mT6KenqaulNlyTBrzm8uUfd7bthAS7OrjCSIiplYdKKdHAu7ZQ1UvZE3SpU=,iv:kWKumMRYGtN9kkBa/nozt+HcT+ORnhjUxNm+cDtCx+Y=,tag:L5RD8EnsnVUM9sbNpSh0yg==,type:str]
    version: 3.13.1
