---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-28
  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB

  # HA: ensure primary and replica on different nodes
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  resources:
    requests:
      cpu: 500m
    limits:
      memory: 1Gi

  monitoring:
    enablePodMonitor: true

  # Backup to S3-compatible storage (Cloudflare R2)
  backup:
    barmanObjectStore:
      destinationPath: s3://backups/cnpg
      endpointURL: https://47dc2e8ccaf9538255dd55cb3fc09e7c.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-secret
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
    retentionPolicy: "30d"

  managed:
    roles:
      - name: vaultwarden
        ensure: present
        login: true
        passwordSecret:
          name: cnpg-vaultwarden-secret
