kind: Secret
apiVersion: v1
type: kubernetes.io/basic-auth
metadata:
    name: cloudnative-pg-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:KaDcowM=,iv:ih2BE++mXBA0/XLNlhIF9KQwcthn78cLcmRDEBxg3B8=,tag:tep7pAJpbJ9Ur6PX9QstGQ==,type:str]
    password: ENC[AES256_GCM,data:CpOvkVGq0A+dZUYwa8a3RvT5Pn6PiLJXaU2AmHZWLMX8sOI+Dyvp3hmnl+i7POgPVZ3S9Fs/Ax2k/Cg4,iv:C4720oSO28sKc3DYrnTmxu4HVuBrfAB3CN7TUHRCmtY=,tag:g5eIPuJgRTGtWGBahPpYZw==,type:str]
sops:
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUTR5WlZwSkpJUmkyWEl4
            R0lUeVlRaDBPM0xYV2t6UDRJUFQ5aGdPU1NzClNuaCs2WG54V1JSQ0tmUWJVRjYr
            T2xvcWpKbHBER3huQjJvQmMzaHZTOHMKLS0tIDV2d3p1SGJwUERINDU4WXhJZkU2
            eVNpQ0NsLy9rS01tTlFMc3pCbWNrK00K4lJQEvXYROmdO0FbjiGEXYTrymPH+Y1v
            A+HtovcqlkphEUe3QRz1/YotIkDAktKbZVNH298GzhTbqMMWXU0qrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T16:02:45Z"
    mac: ENC[AES256_GCM,data:YBPA0QLOo/Aczj/S8GT5PSNZuXwBreAsRMq8eciRnLok1cgosR2aWgl+85ybgSH9l+3vgucabzMHTwKGjYEuFmespbasUXQ4LGn6io/p42Vpjl67+A9kezG0e3pcvJ5PWIHHpOmOApvzU3Yvd1R8YZBNxzgbIJiY6dINv87C338=,iv:k0+o9j1YOh0LqLJ38qiz+fqINawe5LK+QnDVq6NPFOI=,tag:GUswbgHxZMGk/QEtkFfihw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
