---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: containerd-cleanup
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: containerd-cleanup
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  path: ./cluster/apps/kube-system/containerd-cleanup/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
