---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 20.8.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    hostNetwork: true
    deployment:
      kind: DaemonSet
      dnsPolicy: ClusterFirstWithHostNet
    service:
      enabled: true
      single: true
      type: ClusterIP
      loadBalancerSourceRanges: []
      externalIPs:
        - 94.237.55.69
        - 94.237.48.88
    globalArguments: []
    logs:
      general:
        level: INFO
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: '{{ template "traefik.name" . }}'
                app.kubernetes.io/instance: "{{ .Release.Name }}-{{ .Release.Namespace }}"
            topologyKey: kubernetes.io/hostname
