---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 20.8.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    service:
      enabled: true
      single: true
      type: NodePort
      loadBalancerSourceRanges: []
      externalIPs:
        - 94.237.55.69
        - 94.237.48.88
    globalArguments: []
    logs:
      general:
        level: INFO
