apiVersion: v1
kind: Secret
metadata:
    name: arr-secrets
    namespace: arr
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:8RBA9CnaIRZE+okMPQATNO3gFy7Vryi8hKiNuxs83CA=,iv:yQp4IG4m3a4Ajt0lo6WoW8MCKmG7g/fYaQEltSY15pY=,tag:DdchaW11uEhoVCGVEaBmAA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:DKOsvloKQlxRhdPjZ7/jn2Jg0kUu2dgnVW8kRBtL7cs=,iv:ykjY/MCTPpeXxgJx0RicWpNQxNic8wJpcY4UIxtWtQQ=,tag:7VlqvWa6EOHMtFKvgxL0/g==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:oHBqOg1OPZWmuEZip8uEXLdr+YY/Ep2E1muEIiHpr+s=,iv:f1cB8TEsoyJSmgo7tZ2aPsBfrRGwHiQ0GwXmDkDJ68s=,tag:xgotYb4GxOipAOJ66OpFEw==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:EwvFai+8zI0sXpAM5cAV25H6nlnVZwPScG/F2LaFlwc=,iv:frY+Yygk2HHDRkIVWHJLLkezeg01YhuXQTbGOGMqcbA=,tag:HsAb1LxLHHjL16xRai7Zyw==,type:str]
    JELLYSTAT_DB_PASSWORD: ENC[AES256_GCM,data:2s6MzT2yLvTeV31jFdPm1Ty/Ldysz4htLwNbS8ie9m8=,iv:aCppI6mrzDxJNoLRAUoPd4y/fdQRBXgKnt3Qoo4/w7s=,tag:IhdRbrZQvJdaA4MF+QtRTQ==,type:str]
    JELLYSTAT_JWT_SECRET: ENC[AES256_GCM,data:Or9Rd2qH+FQiB66SV7MtYEkp7nBPDnjWcAxMA/R6rsHzlxjb0lW+CmdvtSGqq047gj0FJTJG7M9DDdtel+Kqlg==,iv:eusFgc4o9EezJb5/GgCrXj70c6nYoPcz1Oe9Ln5wIvw=,tag:T+tkGBNK+PVLeE+PpB3p3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUelNCTlBuTEhOaFU0WlNn
            VnU5RUVOTGttaXlVN01MT2I5Umw4enpqdUNjCkJsQjlWTjNmZjA5SUU4L3NRblZx
            UnVtNUFWK2hrbW5XVmxIYmtCM0RsaFUKLS0tIHRVRytSMmlDR25NMWRYSFdqWDBm
            ZEx1cnErRjNFK21LMktXZkQ1ZDhjRWsKbta5kg2+cNjWxPHhtSO6RPev4XWosMAa
            NavNzOWCB+FvQKbYazCHjc15vp/Hjmuibv69xvMSc/ZkB1EM9XD4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T15:14:11Z"
    mac: ENC[AES256_GCM,data:7dnnYIVBUYS5NoQa60rn2FCDXPYDp3ERvjW9MPMC2ukG6jDnw1vRPnz9bpEOKxjJXySFxd/CQHrz3SIv3p6dhEHQGjuA0NM2Embpsau8Yu8jsQtO6hLcUCpzzxNDXi9SAxmqIEgNy9yS0nY9Kxn13mfccf+XNpUwL1xnSo5+hwY=,iv:UGqP9ZShzITu7HXpxw5Y42OVvKVRLXKbPisGyjoAq5I=,tag:TvMO6b/Eugi5P7X4kq7IkQ==,type:str]
    version: 3.13.1
