---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smokeping
spec:
  releaseName: *app
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/smokeping
              tag: "version-2.7.3-r5"
            env:
              TZ: Europe/Paris
              PUID: "1000"
              PGID: "1000"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
          exporter:
            image:
              repository: quay.io/superq/smokeping-prober
              tag: v0.10.0
            args:
              - --privileged
              - 1.1.1.1
              - 8.8.8.8
              - cluster.kaminek.me
            securityContext:
              capabilities:
                add:
                  - NET_RAW
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
          metrics:
            port: 9374
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ping.kaminek.me
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: "https://oauth.kaminek.me/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth.kaminek.me/oauth2/start?rd=$scheme://$host$request_uri"
          hajimari.io/enable: "true"
          hajimari.io/icon: lan-pending
          hajimari.io/group: Monitoring
          hajimari.io/appName: SmokePing
        hosts:
          - host: &uri ping.kaminek.me
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: smokeping-tls
    persistence:
      data:
        existingClaim: smokeping-data
        globalMounts:
          - path: /data
      config:
        existingClaim: smokeping-config
        globalMounts:
          - path: /config
    serviceMonitor:
      main:
        endpoints:
          - port: metrics
