---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smokeping
spec:
  releaseName: *app
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/smokeping
              tag: "version-2.7.3-r5"
            env:
              TZ: Europe/Paris
              PUID: "1000"
              PGID: "1000"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ping.kaminek.me
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &uri ping.kaminek.me
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: smokeping-tls
    persistence:
      data:
        existingClaim: smokeping-data
        globalMounts:
          - path: /data
      config:
        existingClaim: smokeping-config
        globalMounts:
          - path: /config
