---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
