apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    CF_API_EMAIL: ENC[AES256_GCM,data:CtdOjeBWsQ733iCCH/8saytRvw==,iv:zuE7ntiH5UvyiBVtU44PeTD7JS7KGHkow9OMPbuZKsU=,tag:R3UD/4vM4nQOSruTmJ0Nnw==,type:str]
    CF_API_KEY: ENC[AES256_GCM,data:sytCojxRj1wTEb/vC6cyu57nmDpStvlMd/RwmeCSqE2mPif0SAE+,iv:olEJXntBNZl9oGNUKQMb+LVfdhsBDWZUKp7YoxNSxyQ=,tag:R2xT9WYvV+TeNQK+yWqOkw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:33CFTlNFyoJpxrXXSPzEWRJ8vuQkZlM+,iv:yTq/dRkS2UKFmtVeyKoICNPrd4qcTS4t2p2WHMKmEzg=,tag:Cfxjv+HQtfg+2BcaUbGpbA==,type:str]
sops:
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWnhIN2IzbUVROG1nVTZL
            bktnRGl2SEtpZUx5UW1EeDV2Y1V5amtzdXdVCklFRXhRU2V0dFBlTERZZ3hLb0x4
            TzJIVDNjelRTWGxOTnJWYUdMRWRzeUkKLS0tIHkrTGtVUk5BV3prMnNlUjdnc1Ew
            L0lrSUc1S2o1dHJkM21IdlVGaUNob0EK9DNnk8J4tohitq0b5gO1U6NLQsGzwKp7
            g/HxDucv6sele8cAJtqNgdqVQOmOGsIPgzIrwFnQZMK+R0hrn5BqFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:31:05Z"
    mac: ENC[AES256_GCM,data:o7yZFvGNNZxZn+4rFdzG5KC0jRGFaY6oPdib3h0d+XZt7Axxr/6TNxqK36kkay6rPrKb2kNY442JsEtKVFhga0zgb0gfuT/iKP7f77q2t8zUh/95PtFCD4k0jZJUGx9IrUDIGv5qF0yZ1TCB7dpb3ttWzvY4EBc1a1379Na4eNg=,iv:BlRB/MiaoT+DP6G6yO5Y9TPYlJcag//fAytcZkz/Krc=,tag:0fzqowlLLGUtxnbkZY7WBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
