apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    CF_API_EMAIL: ENC[AES256_GCM,data:CtdOjeBWsQ733iCCH/8saytRvw==,iv:zuE7ntiH5UvyiBVtU44PeTD7JS7KGHkow9OMPbuZKsU=,tag:R3UD/4vM4nQOSruTmJ0Nnw==,type:str]
    CF_API_KEY: ENC[AES256_GCM,data:sytCojxRj1wTEb/vC6cyu57nmDpStvlMd/RwmeCSqE2mPif0SAE+,iv:olEJXntBNZl9oGNUKQMb+LVfdhsBDWZUKp7YoxNSxyQ=,tag:R2xT9WYvV+TeNQK+yWqOkw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:33CFTlNFyoJpxrXXSPzEWRJ8vuQkZlM+,iv:yTq/dRkS2UKFmtVeyKoICNPrd4qcTS4t2p2WHMKmEzg=,tag:Cfxjv+HQtfg+2BcaUbGpbA==,type:str]
    ADGUARD_ALLOWED_IP: ENC[AES256_GCM,data:uDh0KcOnp2urcA==,iv:cl387sJFceugq+RVIxkmBOHyJcpt65VoFwYCeir5YsA=,tag:fqVbNJZlnn4yGup8hfm0xQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWnhIN2IzbUVROG1nVTZL
            bktnRGl2SEtpZUx5UW1EeDV2Y1V5amtzdXdVCklFRXhRU2V0dFBlTERZZ3hLb0x4
            TzJIVDNjelRTWGxOTnJWYUdMRWRzeUkKLS0tIHkrTGtVUk5BV3prMnNlUjdnc1Ew
            L0lrSUc1S2o1dHJkM21IdlVGaUNob0EK9DNnk8J4tohitq0b5gO1U6NLQsGzwKp7
            g/HxDucv6sele8cAJtqNgdqVQOmOGsIPgzIrwFnQZMK+R0hrn5BqFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T14:35:05Z"
    mac: ENC[AES256_GCM,data:mk9C0ir7CId0ygwYGTC3ilFCi0mnpzeMRN2EoHJUtK4d2720YFLh2SdN23eypPa5QtktqwO23T47MUNlr8FPrWcH8kfuZr5ZqhLZI/VFGmyC+2xdUL7oK6svzXwb+vsSfXa4Cza5QswIRPS/ct3MY5fmXnfcv4/26j0NeXSWzZQ=,iv:CsvNMERCkotQICqk/VHPzpptDkhCOhK0chSMApVcQ5Q=,tag:EeGTCHLDU0OI7YSegwCZpw==,type:str]
    version: 3.11.0
